Adding post on circleci workflow
pagarme/cafe-com-testes pull request #12
Opened 2021-01-18 00:44 UTC by giselerosa

Adicionando um post falando sobre um recurso que facilita as análises referentes a fluxo de trabalho no Circle CI.

2021-01-18 01:07 UTC, PauloGoncalvesBH requested changes

2021-01-18 01:07 UTC, PauloGoncalvesBH commented on artigos/circleci-validate-workflow.md
> +Para isso existe um projeto que estarei compartilhando com vocês , que nasceu com a proposta de nos ajudar nisso. Se você estiver lutando para gerenciar uma configuração complexa do Circle CI 2, você
Não sabia que existia o `Circle CI 2`. Isso é uma ferramenta a parte ou é referente à versão do workflow, que no seu exemplo utiliza a 2.1?

2021-01-18 01:07 UTC, PauloGoncalvesBH commented on artigos/circleci-validate-workflow.md
> +O [Circleci Workflow Validator](https://github.com/JackuB/circleci-workflow-validator) te entrega a possibilidade de pegar o seu arquivo yml, fazer uma leitura dele e gerar pra você ontime o fluxo gr
```suggestion
O [Circleci Workflow Validator](https://github.com/JackuB/circleci-workflow-validator) te entrega a possibilidade de pegar o seu arquivo yml, fazer uma leitura dele e gerar pra você ontime o fluxo gráfico, sem que seja necessário você subir para o Circle CI, e em alguns casos descobrir que faltava algum detalhe ou que tinha algo errado no fluxo.
```

2021-01-18 01:07 UTC, PauloGoncalvesBH commented on artigos/circleci-validate-workflow.md
> +Para melhor entendimento , vamos levar para um cenário prático. Dado que temos a configuração a seguir e queremos validar o fluxo de trabalho dela:
```suggestion
Para melhor entendimento, vamos levar para um cenário prático. Dado que temos a configuração a seguir e queremos validar o fluxo de trabalho dela:
```

2021-01-18 01:07 UTC, PauloGoncalvesBH commented on artigos/circleci-validate-workflow.md
> +Simulando o workflow com a branch master:
```suggestion
Mágico né? Mas tem outra coisa muito legal ainda. Se observar no nosso arquivo yml de exemplo o job `test-integration` roda somente quando está na branch `master`, e para ver isso acontecendo basta que na parte superior do site você coloque a branch `master` e verá esse job no workflow. E caso queira ver o caso em que não é a branch `master` bastará inserir outro nome de branch, como branch `teste` , por exemplo. Então, você visualizará como ficará esse fluxo, isso dará a visibilidade que precisa do fluxo com o filtro e sem o filtro, assim como outros aspectos que sabemos que existem muitos no _Circle CI_.

Veja nas imagens:

Simulando o workflow da branch `teste`:

<p align="left">
  <a href="https://github.com/pagarme/cafe-com-testes">
    <img src="../.github/validator-workflow-ci1.png">
  </a>
</p>

Simulando o workflow com a branch `master`:
```

O que acha desses ajustes para facilitar a visualização das branches e job?

2021-01-18 01:41 UTC, PauloGoncalvesBH requested changes

2021-01-18 01:41 UTC, PauloGoncalvesBH commented on README.md
> +  - [V](#v)
@giselerosa o que acha de não inserir no índice as letras do índice de artigos? Pode acabar sendo bem extenso, levando o conteúdo principal mais para baixo, e já é de fácil acesso dentro do `índice de artigos`.

2021-01-18 01:41 UTC, PauloGoncalvesBH commented on README.md
> +- [🤖 Navegue](#-navegue)
@giselerosa estou em dúvida sobre esse ponto. Seria necessário a inclusão de link para o `navegue` dentro do próprio `navegue`?

2021-01-18 11:25 UTC, samycici commented on artigos/circleci-validate-workflow.md
> +O [CircleCI](https://circleci.com/) é uma ferramenta extremamente complexa, sendo assim, em várias ocasiões nos deparamos com algumas dificuldades sendo uma delas o controle dos fluxos de trabalho. A
eu não  sei se é uma ferramenta extremamente complexa hahah
acho o Jenkins bem pior pq você precisa fazer um monte de coisas na mão que o CircleCI já encapsula.
Eu acho que a maior dificuldade acaba sendo você precisar testar todas as mudanças subindo as alterações e vendo executar lá. Eu mudaria  essa parte

2021-01-18 11:40 UTC, giselerosa commented on artigos/circleci-validate-workflow.md
> +Para isso existe um projeto que estarei compartilhando com vocês , que nasceu com a proposta de nos ajudar nisso. Se você estiver lutando para gerenciar uma configuração complexa do Circle CI 2, você
é referente a versão :)

2021-01-18 11:56 UTC, giselerosa commented on README.md
> +- [🤖 Navegue](#-navegue)
Noooosa, eu estava usando uma extensão no VS Code chamada Markdown All in One e não me atentei que quando salvei o arquivo ele fez essas alterações automaticamente. Vou tentar entender depois o motivo. Arrumei aqui 👍🏽

2021-01-18 12:00 UTC, giselerosa commented on README.md
> +  - [V](#v)
@PauloGoncalvesBH Eu não fiz essa alteração foi algo automático da extensão que eu estava utilizando e não me atentei. Sorry

2021-01-18 12:05 UTC, giselerosa commented on artigos/circleci-validate-workflow.md
> +O [CircleCI](https://circleci.com/) é uma ferramenta extremamente complexa, sendo assim, em várias ocasiões nos deparamos com algumas dificuldades sendo uma delas o controle dos fluxos de trabalho. A
Concordo com seus pontos haha, talvez eu ainda ache um pouco complexa porque é um mundo novo pra mim. Mas fiz uma alteração aqui e vou subir pra você dar uma olhada.

2021-01-18 14:45 UTC, PauloGoncalvesBH requested changes

2021-01-18 14:45 UTC, PauloGoncalvesBH commented on artigos/circleci-validate-workflow.md
> +<p align="left">
```suggestion
Mágico né? Mas tem outra coisa muito legal ainda. Se observar no nosso arquivo yml de exemplo o job `test-integration` roda somente quando está na branch `master`, e para ver isso acontecendo basta que na parte superior do site você coloque a branch `master` e verá esse job no workflow. E caso queira ver o caso em que não é a branch `master` bastará inserir outro nome de branch, como branch `teste` , por exemplo. Então, você visualizará como ficará esse fluxo, isso dará a visibilidade que precisa do fluxo com o filtro e sem o filtro, assim como outros aspectos que sabemos que existem muitos no _Circle CI_.

Veja nas imagens:

Simulando o workflow da branch `teste`:

<p align="left">
  <a href="https://github.com/pagarme/cafe-com-testes">
    <img src="../.github/validator-workflow-ci1.png">
  </a>
</p>

Simulando o workflow com a branch `master`:

<p align="left">
```
@giselerosa é preciso ter uma linha em branco entre os parágrafos para que todo o conteúdo não acabe ficando na mesma linha,
Ou, se preferir, pode adicionar `<br>` ao fim da linha.

2021-01-18 14:51 UTC, PauloGoncalvesBH requested changes

2021-01-18 14:51 UTC, PauloGoncalvesBH commented on artigos/circleci-validate-workflow.md
> +O [CircleCI](https://circleci.com/) é uma ferramenta que tem por necessidade em casos de novos projetos ou mudanças, subirmos as alterações que fazemos e acompanharmos a execução lá. Sendo assim, em
```suggestion
O [CircleCI](https://circleci.com/) é uma ferramenta que tem a necessidade de, em casos de novos projetos ou mudanças, subirmos as alterações que fazemos e acompanharmos a execução lá. Sendo assim, em várias ocasiões nos deparamos com algumas dificuldades sendo uma delas o controle dos fluxos de trabalho. A ideia desse artigo é que você possa visualizar de forma gráfica o fluxo de trabalho e possa visualizar eles em diferentes branches para nos ajudar naqueles casos mais complexos em que as rotinas e fluxos variam de acordo com a branch em execução.
```
@giselerosa acredito que é preciso uma pequena alteração no começo do parágrafo para facilitar o entendimento da ideia que quer passar.
Tentei pensar em uma solução, que é a que sugiro acima, mas acredito que ainda não está 100% adequado. O que acha de tentar verificar esse trecho?
Se também não tiver ideia e eu já tiver um meio de comunicação por voz com você, podemos ver juntos o que ficaria melhor.

2021-01-21 20:21 UTC, PauloGoncalvesBH approved these changes

2021-02-10 20:58 UTC, samycici requested changes

2021-02-10 20:58 UTC, samycici commented on artigos/circleci-validate-workflow.md
> +O [Circleci Workflow Validator](https://github.com/JackuB/circleci-workflow-validator) te entrega a possibilidade de pegar o seu arquivo yml, fazer uma leitura dele e gerar pra você ontime o fluxo gr
```suggestion
O [Circleci Workflow Validator](https://github.com/JackuB/circleci-workflow-validator) te entrega a possibilidade de pegar o seu arquivo yml, fazer uma leitura dele e gerar pra você em tempo real o fluxo gráfico, sem que seja necessário você subir para o Circle CI, e em alguns casos descobrir que faltava algum detalhe ou que tinha algo errado no fluxo.
```

2021-02-10 21:03 UTC, samycici approved these changes

2021-02-10 21:03 UTC, merged