Adicionando um novo artigo
pagarme/cafe-com-testes pull request #20
Opened 2023-11-17 13:24 UTC by Aureojj

O que esse PR faz?

Adiciona um novo artigo dentro dos padrões do repositório com o tema:  Alternativas ao uso do {force: true} nos comandos do Cypress.

2023-11-17 13:56 UTC, vannessasoares approved these changes

2023-11-17 14:05 UTC, paulofachini approved these changes

2023-11-17 14:49 UTC, gabriellealvim approved these changes

2023-11-17 15:50 UTC, bemenezes approved these changes
Muito bomm @Aureojj!!! Parabéns!

2023-11-17 18:42 UTC, PauloGoncalvesBH requested changes
Oi @Aureojj, seu texto está ótimo, bem claro e com boa escolha de tópicos. Mandou muito bem 🤟🏼.

Fiz algumas sugestões que são voltadas para tornar a leitura mais fluida, o que acha sobre elas?

2023-11-17 18:42 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +# Quais alternativas podemos utilizar?
```suggestion
## Quais alternativas podemos utilizar?
```

O que achar de colocar esse como subtópico?
Já que faz parte do contexto de como evitar a sua utilização, e para evitar devemos saber outras alternativas.

2023-11-17 18:42 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +Quando estamos escrevendo Testes e2e no Cypress, precisamos realizar ações, como: clicar em um botão, digitar em um campo de texto, selecionar uma opção em um menu suspenso etc. No entanto, às vezes,
```suggestion
Quando estamos escrevendo Testes e2e no Cypress, precisamos realizar ações, como: Clicar em um botão, digitar em um campo de texto, selecionar uma opção em um menu suspenso, etc. No entanto podemos encontrar situações em que os elementos da página não estão visíveis ou habilitados para a interação. Por exemplo: um botão pode estar escondido por um modal, um campo de texto pode estar desabilitado até que uma condição seja satisfeita, uma opção em um menu suspenso pode estar fora da área visível da tela etc. Nesses casos, o Cypress irá falhar ao tentar interagir com esses elementos, pois ele segue as mesmas regras que um usuário real seguiria, ou seja, ele só irá interagir com elementos que estão visíveis e habilitados. Mas e se quisermos forçar a interação com esses elementos, mesmo que eles não estejam em um estado adequado para isso? É aí que entra o `{force: true}`.
```

Texto está ótimo, pequenos ajustes só para tornar a leitura mais fluida.

2023-11-17 18:42 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +O {force: true} é um argumento opcional que podemos passar para as ações do Cypress, como .click(), .type(), .select() etc. Ele faz com que o Cypress ignore as verificações de visibilidade e habilita
```suggestion
O `{force: true}` é um argumento opcional que podemos passar para as ações do Cypress, como .click(), .type(), .select() etc. Ele faz com que o Cypress ignore as verificações de visibilidade e habilitação dos elementos e execute a ação de qualquer forma.
```

2023-11-17 18:42 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +# Por que devemos evitar a utilização?
```suggestion
# Em quais cenários devemos evitar a utilização?
```
O que acha de fazer esse ajuste para manter um título relacionado à seção anterior?

2023-11-17 18:42 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +- Usar comandos, como .should('be.visible') ou .should('not.be.disabled') para verificar as condições dos elementos antes de interagir com eles;
```suggestion
- Usar comandos, como `.should('be.visible')` ou `.should('not.be.disabled')` para verificar as condições dos elementos antes de interagir com eles;
```

2023-11-17 18:42 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +- Usar comandos, como .scrollIntoView() ou .trigger('mouseover') para tornar os elementos visíveis ou acessíveis;
```suggestion
- Usar comandos, como `.scrollIntoView()` ou `.trigger('mouseover')` para tornar os elementos visíveis ou acessíveis;
```

2023-11-17 18:42 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +- Usando o método em JavaScript .dispatchEvent() para simular uma ação, no caso abaixo, disparamos um evento do tipo 'mouseover' simulanto o comportamento do usuário passando o mouse sobre o elemento
```suggestion
- Usando o método em JavaScript `.dispatchEvent()` para simular uma ação, no caso abaixo, disparamos um evento do tipo _'mouseover'_ simulanto o comportamento do usuário passando o mouse sobre o elemento.
```

2023-11-17 18:42 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +      })
```suggestion
})
```

2023-11-17 18:42 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +Essas são algumas das alternativas ao uso do {force: true} no Cypress que podem tornar os testes mais confiáveis, legíveis e manuteníveis.
```suggestion
Essas são algumas das alternativas ao uso do `{force: true}` no Cypress que podem tornar os testes mais confiáveis, legíveis e manuteníveis.
```

2023-11-17 18:44 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +Referências:
```suggestion
---
## Referências:
```

2023-11-17 18:51 UTC, PauloGoncalvesBH commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +No entanto, o uso do {force: true} também tem seus riscos e desvantagens, como:
```suggestion
No entanto, o uso do `{force: true}` também tem seus riscos e desvantagens, como:
```

2023-11-17 18:56 UTC, Aureojj commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +# Quais alternativas podemos utilizar?
Faz total sentido, fora que, melhora a visibilidade e leitura do artigo.

2023-11-18 17:08 UTC, PauloGoncalvesBH approved these changes
![Friends Clap](https://media3.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif?cid=47028fa81rda1t2f7b12e0cyh0rlj4hnehstygaulemz4h55&ep=v1_gifs&rid=giphy.gif&ct=g)

2023-11-21 21:16 UTC, giselerosa approved these changes

2023-11-22 11:33 UTC, dayaneCsantos commented on artigos/cypress-alternativas-ao-uso-do-force.md
> +cy.get('#meu-botao').should('not.be.disabled').click(); // Valida que o elemento indicado está visível e simula o click do mouse
Em vez de "Valida que o elemento indicado está visível" acho que poderia ser "Valida que o elemento indicado não está desabilitado" algo desse tipo

2023-11-28 21:26 UTC, merged