Giselerosa cypress variaveis de ambiente
pagarme/cafe-com-testes pull request #7
Opened 2020-11-06 19:58 UTC by giselerosa

Artigo falando sobre variáveis de ambiente com o Cypress.

2020-11-06 19:59 UTC, giselerosa commented
@samycici Segue o artigo sobre o cypress.

2020-11-06 20:22 UTC, PauloGoncalvesBH requested changes
@giselerosa vim dar o review de penetra rs. O texto ficou ótimo, aprendi lendo ele. Abri algumas sugestões que são apenas de formatação, nada de conteúdo, pois, novamente, está ótimo.
Outra alteração que é necessária. O arquivo está sem extensão, é preciso colocar _.md_ no final, ficando assim o nome: `cypress-variaveis-de-ambiente.md`

2020-11-06 20:22 UTC, PauloGoncalvesBH commented on artigos/cypress-variaveis-de-ambiente
> +O Cypress oferece várias maneiras de trabalhar com variáveis de ambiente. Em sua [documentação](https://docs.cypress.io/guides/guides/environment-variables.html#Setting) sobre variáveis de ambiente l
O _markdown_ não reconhece que é um parágrafo diferente. Sem essa linha em branco sugerida fica tudo no mesmo parágrafo, e a leitura fica atrapalhada.
```suggestion

O Cypress oferece várias maneiras de trabalhar com variáveis de ambiente. Em sua [documentação](https://docs.cypress.io/guides/guides/environment-variables.html#Setting) sobre variáveis de ambiente listou seus usos e comparando os prós / contras de cada opção. 
```

2020-11-06 20:22 UTC, PauloGoncalvesBH commented on artigos/cypress-variaveis-de-ambiente
> +## Benefícios
Já que é uma subseção de _Arquivo de configuração da opção # 1_, o que acha de colocar em um novo nível essa seção?
```suggestion
### Benefícios
```

2020-11-06 20:22 UTC, PauloGoncalvesBH commented on artigos/cypress-variaveis-de-ambiente
> +##  Desvantagens
Já que é uma subseção de _Arquivo de configuração da opção # 1_, o que acha de colocar em um novo nível essa seção?
```suggestion
###  Desvantagens
```

2020-11-06 20:22 UTC, PauloGoncalvesBH commented on artigos/cypress-variaveis-de-ambiente
> +##Benefícios
Já que é uma subseção de _Opção nº 2 cypress.env.json_, o que acha de colocar em um novo nível essa seção?
```suggestion
### Benefícios
```

2020-11-06 20:22 UTC, PauloGoncalvesBH commented on artigos/cypress-variaveis-de-ambiente
> +## Desvantagens
Já que é uma subseção de _Opção nº 2 cypress.env.json_, o que acha de colocar em um novo nível essa seção?
```suggestion
### Desvantagens
```

2020-11-06 20:52 UTC, giselerosa reviewed
@PauloGoncalvesBH Obrigada pelas dicas! Fiz as alterações aqui o/

2020-11-06 20:52 UTC, giselerosa commented on artigos/cypress-variaveis-de-ambiente
> +## Desvantagens
Ótima sugestão, fiz aqui :)

2020-11-06 20:52 UTC, giselerosa commented on artigos/cypress-variaveis-de-ambiente
> +##Benefícios
Ótima sugestão, fiz aqui :)

2020-11-06 20:52 UTC, giselerosa commented on artigos/cypress-variaveis-de-ambiente
> +##  Desvantagens
Ótima sugestão, fiz aqui :)

2020-11-06 20:52 UTC, giselerosa commented on artigos/cypress-variaveis-de-ambiente
> +O Cypress oferece várias maneiras de trabalhar com variáveis de ambiente. Em sua [documentação](https://docs.cypress.io/guides/guides/environment-variables.html#Setting) sobre variáveis de ambiente l
Boa! Realmente fica melhor de ler com a separação do parágrafo.

2020-11-06 20:53 UTC, PauloGoncalvesBH requested changes

2020-11-06 20:53 UTC, PauloGoncalvesBH commented on artigos/cypress-variaveis-de-ambiente.md
> +# Settting
Ops, acabou passando a letra T a mais.

```suggestion
# Setting
```

2020-11-06 21:01 UTC, giselerosa commented on artigos/cypress-variaveis-de-ambiente.md
> +# Settting
Ops rsrs

2020-11-06 21:03 UTC, PauloGoncalvesBH approved these changes

2020-11-06 21:36 UTC, samycici requested changes

2020-11-06 21:36 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +O Cypress oferece várias maneiras de trabalhar com variáveis de ambiente. Em sua [documentação](https://docs.cypress.io/guides/guides/environment-variables.html#Setting) sobre variáveis de ambiente l
esse parágrafo ficou meio confuso, 'listou seus usos e comparando os prós / contras de cada opção. ' isso aqui é que a documentação lista os usos?

2020-11-06 21:36 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +4. Você pode alterar facilmente as variáveis de ambiente, especialmente quando estiver executando em CI.
acho que vale incluir a questão de segurança, quando é uma credencial por exemplo que não pode ficar exposta

2020-11-06 21:36 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +Ao invés de codificar isso nas suas automatizações
```suggestion
Ao invés de colocar diretamente no seu código
```

2020-11-06 21:36 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +Você pode mover isso para uma variável de ambiente Cypress como exemplificando abaixo , em que foi criada uma variável de ambiente chamada EXTERNAL_API deixando o código com uma melhor manutenibilida
```suggestion
Você pode mover para uma variável de ambiente Cypress como exemplificando abaixo, em que foi criada uma variável de ambiente chamada EXTERNAL_API deixando o código com uma melhor manutenibilidade e liberdade de execução em diferentes ambientes.
```

2020-11-06 21:36 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +Existem diferentes de definir variáveis de ambiente. Cada um deles tem um caso de uso ligeiramente diferente.
```suggestion
Existem diferentes formas de definir variáveis de ambiente. Cada uma delas tem um caso de uso ligeiramente diferente.
```

2020-11-06 21:36 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +```
```suggestion
```json
{
  "projectId": "128076ed-9868-4e98-9cef-98dd7a705d75",
  "env": {
    "login_url": "/login",
    "login_user":"usuariomaster",
    "login_password": "Senha123"
  }
}
```
```

2020-11-06 21:36 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +```
faltou uma vírgula no json

2020-11-06 21:36 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +Alternativamente, você pode decidir criar seu próprio arquivo cypress.env.json que o Cypress irá criar automaticamente. Os valores neste arquivo sobrescreverão variáveis de ambiente conflitantes em s
ficou estranho "você criar seu próprio arquivo... que o cypress irá criar automaticamente"

2020-11-07 21:08 UTC, giselerosa commented on artigos/cypress-variaveis-de-ambiente.md
> +O Cypress oferece várias maneiras de trabalhar com variáveis de ambiente. Em sua [documentação](https://docs.cypress.io/guides/guides/environment-variables.html#Setting) sobre variáveis de ambiente l
Isso , a documentação lista diferentes formas de uso , com seus prós e contra. Vou reformular o parágrafo de forma a ficar mais claro.

2020-11-08 22:18 UTC, samycici requested changes

2020-11-08 22:18 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +O Cypress oferece várias maneiras de trabalhar com variáveis de ambiente. Em sua [documentação](https://docs.cypress.io/guides/guides/environment-variables.html#Setting) sobre variáveis de ambiente s
```suggestion
O Cypress oferece várias maneiras de trabalhar com variáveis de ambiente. Em sua [documentação](https://docs.cypress.io/guides/guides/environment-variables.html#Setting) sobre variáveis de ambiente são listadas diferentes opções demonstrando o seu uso, e também prós e contras de cada abordagem.
```

2020-11-08 22:18 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +O Cypress oferece várias maneiras de trabalhar com variáveis de ambiente. Em sua [documentação](https://docs.cypress.io/guides/guides/environment-variables.html#Setting) sobre variáveis de ambiente s
ficou um espaço antes da vírgula

2020-11-08 22:18 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +5. Existem valores protegidos que não podem ser expostos por segurança
```suggestion
5. Você está lidando com credenciais que não podem ser expostas por segurança
```

2020-11-09 12:55 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +Frequentemente, precisamos escrever testes e2e para verificação de processos que solicitam recursos protegidos, que exigem credenciais apropriadas. Por exemplo, um formulário de login que espera um n
```suggestion
Frequentemente, precisamos escrever testes e2e para verificação de processos que solicitam recursos protegidos, que exigem credenciais apropriadas. Por exemplo, um formulário de login que espera um nome de usuário e senha válidos, um terminal que usa uma chave API, uma solicitação HTTP que precisa de um token verificável. Uma das abordagens comuns é salvar os dados protegidos como variáveis de ambiente.
```

2020-11-09 12:55 UTC, samycici commented on artigos/cypress-variaveis-de-ambiente.md
> +Frequentemente, precisamos escrever testes e2e para verificação de processos que solicitam recursos protegidos, que exigem credenciais apropriadas. Por exemplo, um formulário de login que espera um n
ficou um espaço perdido aqui tb, sorry não ter visto ontem

2020-11-09 14:39 UTC, merged