feat: artigo allure report
pagarme/cafe-com-testes pull request #8
Opened 2020-11-13 12:35 UTC by btfshadow

Artigo Allure report

2020-11-13 21:07 UTC, samycici requested changes

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +  reporter.addAttachment(name: string, buffer: any, type: string)
```suggestion
```javascript
reporter.addAttachment(name: string, buffer: any, type: string)
```

```

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +  No caso 'body', mas aqui pode ser qualquer string.
```suggestion
O primeiro parâmetro é o nome que aparecer no anexo. No caso 'body', mas aqui pode ser qualquer string.
```

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +  No caso 'body', mas aqui pode ser qualquer string.
fiquei confusa com o body, de onde saiu isso? Não deu pra entender muito bem

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +  Segundo é o contéudo, um texto, uma imagem, um video, um CSV entre outros.
```suggestion
O segundo se refere ao contéudo, que pode ser um texto, uma imagem, um vídeo, um CSV entre outros. 
```

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +
```suggestion
O terceito é o tipo do arquivo que você está anexando, em alguma linguagens existe um enum que facilita esse ponto.

```

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +    JS
esse JS tá perdido aqui?

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +    '''Ruby'''
esse Ruby significa o quê?

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +    "image/jpeg"
```suggestion
* "text/plain"
* "application/xml"
* "text/csv"
* "text/tab-separated-values"
* "text/css"
* "text/uri-list"
* "image/svg+xml"
* "image/png"
* "application/json"
* "video/webm"
* "image/jpeg"
```

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +  Aqui vai uma dica de tipo de arquivos que podemos adicionar.
```suggestion
  Aqui vai uma dica de tipos de arquivos que podemos adicionar:
```

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +### Exemplo de como fica.
```suggestion
### Exemplo
```

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> + ## Beneficios
```suggestion
 ## Benefícios 
```

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +  Centralizar a informação em um unico lugar
```suggestion
* Ter mais informações, que já são geradas nos testes; 
* Centralizar as informações em um único lugar;
```

2020-11-13 21:07 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +
```suggestion
Você literalmente pode armazenar quanta informação quiser e isso pode fazer com que você tenha problemas com espaço, dependendo de onde o seu relatório é geraodo. 

```

2020-11-18 12:43 UTC, btfshadow reviewed
mudanças efetuadas

2020-11-18 17:34 UTC, samycici commented
@btfshadow faz um slash dos commits pra deixar um só

2020-11-18 17:39 UTC, samycici requested changes

2020-11-18 17:39 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +Como o Allure tem suporte para várias linguagens, e às vezes existem diferenças na integração, eu aconselho a olhar na documentação como é feito especificamente para a linguagem/framework que você es
```suggestion
Como o Allure tem suporte para várias linguagens, e às vezes existem diferenças na integração, eu aconselho a olhar na [documentação](http://allure.qatools.ru/) como é feito especificamente para a linguagem/framework que você está utilizando.
```

2020-11-18 17:39 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +reporter.addAttachment(name: string, buffer: any, type: string)
aqui na linha 31 vc tem que colocar ``` para fechar o bloco de código

2020-11-18 17:39 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +Allure.add_attachment(name: "attachment", source: "Some string", type: Allure::ContentType::TXT, test_case: false)
aqui na linha 36 vc tem que colocar ``` para fechar o bloco de código

2020-11-18 17:39 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +Lembrando que os as linhas de código podem ser adicionadas a qualquer momento do teste. Apenas se certifique se de ter a informação que deseja anexar.
```suggestion
Lembrando que os as linhas de código podem ser adicionadas a qualquer momento do teste. Apenas se certifique de ter a informação que deseja anexar.
```

2020-11-18 17:39 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +reporter.addAttachment(name: string, buffer: any, type: string)
aqui na linha 58 vc tem que colocar ``` para fechar o bloco de código

2020-11-19 12:37 UTC, btfshadow commented on artigos/allure-conteudo-no-report.md
> +Allure.add_attachment(name: "attachment", source: "Some string", type: Allure::ContentType::TXT, test_case: false)
feito

2020-11-19 12:37 UTC, btfshadow commented on artigos/allure-conteudo-no-report.md
> +reporter.addAttachment(name: string, buffer: any, type: string)
feito

2020-11-19 12:38 UTC, btfshadow commented on artigos/allure-conteudo-no-report.md
> +Lembrando que os as linhas de código podem ser adicionadas a qualquer momento do teste. Apenas se certifique se de ter a informação que deseja anexar.
feito

2020-11-19 12:39 UTC, btfshadow commented on artigos/allure-conteudo-no-report.md
> +reporter.addAttachment(name: string, buffer: any, type: string)
feito

2020-11-19 17:25 UTC, samycici requested changes

2020-11-19 17:25 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +reporter.addAttachment(name: string, buffer: any, type: string)
trazer para cá a parte de Anexar, para explicar o que é cada parâmetro

2020-11-19 17:25 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +reporter.addAttachment(name: string, buffer: any, type: string)
adicionar logo após algo como: "uma sugestão é utilizá-lo dentro do afterEach e explicar o pq"

2020-11-19 17:25 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +<p align="center">
descrever o que está na imagem: teste X falhou e foi anexado tais coisas

2020-11-19 17:25 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +  Você literalmente pode armazenar quanta informação quiser e isso pode fazer com que você tenha problemas com espaço, dependendo de onde o seu relatório é geraodo.
```suggestion
  Você literalmente pode armazenar quanta informação quiser e isso pode fazer com que você tenha problemas com espaço, dependendo de onde o seu relatório é gerado. 
```

2020-11-19 17:46 UTC, btfshadow commented on artigos/allure-conteudo-no-report.md
> +reporter.addAttachment(name: string, buffer: any, type: string)
feito

2020-11-19 17:47 UTC, btfshadow commented on artigos/allure-conteudo-no-report.md
> +<p align="center">
feito

2020-11-19 17:48 UTC, btfshadow commented on artigos/allure-conteudo-no-report.md
> +  Você literalmente pode armazenar quanta informação quiser e isso pode fazer com que você tenha problemas com espaço, dependendo de onde o seu relatório é geraodo.
resolvi aqui

2020-11-19 17:58 UTC, samycici requested changes

2020-11-19 17:58 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +O terceito é o tipo do arquivo que você está anexando, em alguma linguagens existe um enum que facilita esse ponto.
```suggestion
> o primeiro parâmetro é o nome que vai aparecer no anexo, aqui você pode usar qualquer _string_
> o segundo se refere ao conteúdo, que pode ser um texto, uma imagem, um vídeo, um CSV, entre outros. 
> o terceiro é o tipo do arquivo que você está anexando, em alguma linguagens existe um _enum_ que facilita esse ponto.
```

2020-11-19 17:58 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +ou é possivel adicionar a linha de código dentro do 'AfterEach' e os anexos irão para dentro do teste.
```suggestion
Você também pode adicionar essa linha de código dentro do 'AfterEach' e os anexos irão ser adicionados dentro dos resultados de cada um dos seus testes. 
```

2020-11-19 17:58 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +Desta forma não sera obrigatório colocar o "addAttachment" em cada teste, apenas uma vez.
```suggestion
Desta forma não sera obrigatório colocar o "addAttachment" em cada teste, e sim apenas uma vez. 
```

2020-11-19 17:58 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +Lembrando, que 'body' é o nome no qual vai ficar o anexo, e o 'response['body']' é uma variavel global do teste, que fica reclicando com o resultado da reposta da chamada de API.
```suggestion
Lembrando, que 'body' é o nome que será dado ao seu anexo, e o 'response['body']' é uma variável global do teste, que fica reciclando com o resultado da reposta da chamada de API.
```

2020-11-19 17:58 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +Lembrando que os as linhas de código podem ser adicionadas a qualquer momento do teste. Apenas se certifique de ter a informação que deseja anexar.
acho que pode tirar esse parágrafo

2020-11-19 17:58 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +Já quem utilizar o BDD como guia de execução dos testes podemos adicionar o contéudo dentro da Feature, utilizando o afterFeature que alguns frameworks dão suporte.
```suggestion
Já quem utilizar o BDD como guia de execução dos testes pode adicionar o conteúdo dentro da Feature, utilizando o afterFeature que alguns frameworks dão suporte. 
```

2020-11-19 17:58 UTC, samycici commented on artigos/allure-conteudo-no-report.md
> +Na imagem a baixo podemos observar um teste que falhou, e no body do teste temos os anexos de varios tipos, CSV e JPG por exemplo.
```suggestion
Na imagem a baixo podemos observar um teste que falhou, e no body do teste temos os anexos de vários tipos, CSV e JPG por exemplo.
```

2020-11-19 18:00 UTC, btfshadow commented on artigos/allure-conteudo-no-report.md
> +Lembrando que os as linhas de código podem ser adicionadas a qualquer momento do teste. Apenas se certifique de ter a informação que deseja anexar.
feito

2020-11-19 19:17 UTC, samycici approved these changes

2020-11-19 19:17 UTC, merged